const TREE_HEIGHT = 8;
export const DEPOSIT_ACTION_BATCH_SIZE = 8;
export const DEPOSIT_TREE_HEIGHT = TREE_HEIGHT;
export const DATA_TREE_HEIGHT = TREE_HEIGHT;
export const NULLIFIER_TREE_HEIGHT = TREE_HEIGHT;
export const ROOT_TREE_HEIGHT = TREE_HEIGHT;
export const ROLLUP_TX_BATCH_SIZE = 2;
